//letters
var letterArray = "abcdefghijklmnopqrstuvwxyz";

//list of words to choose from
var Words = [
    "apple",
    "asparagus",
    "banana",
    "bed",
    "beets",
    "bird",
    "blue",
    "blueberry",
    "cabbage",
    "camel",
    "carrot",
    "cat",
    "chair",
    "cherry",
    "chicken",
    "corn",
    "cow",
    "cucumber",
    "deer",
    "dog",
    "dolphin",
    "duck",
    "duckling",
    "elephant",
    "furniture",
    "girrafe",
    "goat",
    "grapes",
    "green",
    "horse",
    "kitten",
    "kiwi",
    "lamp",
    "lavender",
    "lemon",
    "lettuce",
    "lime",
    "lion",
    "mango",
    "monkey",
    "onion",
    "orange",
    "papaya",
    "pear",
    "pig",
    "pineapple",
    "pink",
    "potatoe",
    "pumpkin",
    "purple",
    "rabbit",
    "ram",
    "raspberry",
    "red",
    "rhino",
    "sofa",
    "squirrel",
    "stool",
    "strawberry",
    "table",
    "tiger",
    "watermelon",
    "yellow",
    "zebra",
 
]

//Pick random index from Words array
var randomIndex = Math.floor(Math.random()*Words.length);

